ALTER TABLE `Product`
  ADD COLUMN `minimumStock` INTEGER NOT NULL DEFAULT 0,
  ADD COLUMN `cost` DECIMAL(65, 30) NOT NULL DEFAULT 0,
  ADD COLUMN `stockType` VARCHAR(40) NULL,
  ADD COLUMN `stockCategory` VARCHAR(120) NULL,
  ADD COLUMN `brands` VARCHAR(255) NULL,
  ADD COLUMN `application` TEXT NULL,
  ADD COLUMN `dimensions` VARCHAR(191) NULL,
  ADD COLUMN `location` VARCHAR(191) NULL;
